# Form implementation generated from reading ui file 'newTEST3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from logic.board import Board
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
            self.LableMove = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(765, 677)
        Form.setStyleSheet("и")
        self.BoardLabel = QtWidgets.QLabel(parent=Form)
        self.BoardLabel.setGeometry(QtCore.QRect(0, 0, 491, 491))
        self.BoardLabel.setStyleSheet("image:url(design/chess_Figure/1451.jpg)")
        self.BoardLabel.setText("")
        self.BoardLabel.setObjectName("BoardLabel")
        self.wR2 = QtWidgets.QLabel(parent=Form)
        self.wR2.setGeometry(QtCore.QRect(411, 407, 54, 55))
        self.wR2.setStyleSheet("image:url(design/chess_Figure/wR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);\n"
"")
        self.wR2.setText("")
        self.wR2.setObjectName("wR2")
        self.wR1 = QtWidgets.QLabel(parent=Form)
        self.wR1.setGeometry(QtCore.QRect(27, 407, 54, 55))
        self.wR1.setStyleSheet("image:url(design/chess_Figure/wR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);\n"
"")
        self.wR1.setText("")
        self.wR1.setObjectName("wR1")
        self.Piece1 = QtWidgets.QLabel(parent=Form)
        self.Piece1.setGeometry(QtCore.QRect(27, 407, 54, 55))
        self.Piece1.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece1.setText("")
        self.Piece1.setObjectName("Piece1")
        self.Piece2 = QtWidgets.QLabel(parent=Form)
        self.Piece2.setGeometry(QtCore.QRect(82, 407, 54, 55))
        self.Piece2.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece2.setText("")
        self.Piece2.setObjectName("Piece2")
        self.Piece4 = QtWidgets.QLabel(parent=Form)
        self.Piece4.setGeometry(QtCore.QRect(191, 407, 54, 55))
        self.Piece4.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece4.setText("")
        self.Piece4.setObjectName("Piece4")
        self.Piece3 = QtWidgets.QLabel(parent=Form)
        self.Piece3.setGeometry(QtCore.QRect(136, 407, 54, 55))
        self.Piece3.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece3.setText("")
        self.Piece3.setObjectName("Piece3")
        self.Piece7 = QtWidgets.QLabel(parent=Form)
        self.Piece7.setGeometry(QtCore.QRect(356, 407, 54, 55))
        self.Piece7.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece7.setText("")
        self.Piece7.setObjectName("Piece7")
        self.Piece6 = QtWidgets.QLabel(parent=Form)
        self.Piece6.setGeometry(QtCore.QRect(301, 407, 54, 55))
        self.Piece6.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece6.setText("")
        self.Piece6.setObjectName("Piece6")
        self.Piece5 = QtWidgets.QLabel(parent=Form)
        self.Piece5.setGeometry(QtCore.QRect(246, 407, 54, 55))
        self.Piece5.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece5.setText("")
        self.Piece5.setObjectName("Piece5")
        self.Piece8 = QtWidgets.QLabel(parent=Form)
        self.Piece8.setGeometry(QtCore.QRect(411, 407, 54, 55))
        self.Piece8.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece8.setText("")
        self.Piece8.setObjectName("Piece8")
        self.Piece58 = QtWidgets.QLabel(parent=Form)
        self.Piece58.setGeometry(QtCore.QRect(82, 28, 54, 55))
        self.Piece58.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece58.setText("")
        self.Piece58.setObjectName("Piece58")
        self.Piece57 = QtWidgets.QLabel(parent=Form)
        self.Piece57.setGeometry(QtCore.QRect(27, 28, 54, 55))
        self.Piece57.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece57.setText("")
        self.Piece57.setObjectName("Piece57")
        self.Piece60 = QtWidgets.QLabel(parent=Form)
        self.Piece60.setGeometry(QtCore.QRect(191, 28, 54, 55))
        self.Piece60.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece60.setText("")
        self.Piece60.setObjectName("Piece60")
        self.Piece59 = QtWidgets.QLabel(parent=Form)
        self.Piece59.setGeometry(QtCore.QRect(136, 28, 54, 55))
        self.Piece59.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece59.setText("")
        self.Piece59.setObjectName("Piece59")
        self.Piece62 = QtWidgets.QLabel(parent=Form)
        self.Piece62.setGeometry(QtCore.QRect(301, 28, 54, 55))
        self.Piece62.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece62.setText("")
        self.Piece62.setObjectName("Piece62")
        self.Piece61 = QtWidgets.QLabel(parent=Form)
        self.Piece61.setGeometry(QtCore.QRect(246, 28, 54, 55))
        self.Piece61.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece61.setText("")
        self.Piece61.setObjectName("Piece61")
        self.Piece63 = QtWidgets.QLabel(parent=Form)
        self.Piece63.setGeometry(QtCore.QRect(356, 28, 54, 55))
        self.Piece63.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece63.setText("")
        self.Piece63.setObjectName("Piece63")
        self.Piece64 = QtWidgets.QLabel(parent=Form)
        self.Piece64.setGeometry(QtCore.QRect(411, 28, 54, 55))
        self.Piece64.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece64.setText("")
        self.Piece64.setObjectName("Piece64")
        self.Piece10 = QtWidgets.QLabel(parent=Form)
        self.Piece10.setGeometry(QtCore.QRect(82, 353, 54, 55))
        self.Piece10.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece10.setText("")
        self.Piece10.setObjectName("Piece10")
        self.Piece9 = QtWidgets.QLabel(parent=Form)
        self.Piece9.setGeometry(QtCore.QRect(27, 353, 54, 55))
        self.Piece9.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece9.setText("")
        self.Piece9.setObjectName("Piece9")
        self.Piece11 = QtWidgets.QLabel(parent=Form)
        self.Piece11.setGeometry(QtCore.QRect(136, 353, 54, 55))
        self.Piece11.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece11.setText("")
        self.Piece11.setObjectName("Piece11")
        self.Piece12 = QtWidgets.QLabel(parent=Form)
        self.Piece12.setGeometry(QtCore.QRect(191, 353, 54, 55))
        self.Piece12.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece12.setText("")
        self.Piece12.setObjectName("Piece12")
        self.Piece13 = QtWidgets.QLabel(parent=Form)
        self.Piece13.setGeometry(QtCore.QRect(246, 353, 54, 55))
        self.Piece13.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece13.setText("")
        self.Piece13.setObjectName("Piece13")
        self.Piece15 = QtWidgets.QLabel(parent=Form)
        self.Piece15.setGeometry(QtCore.QRect(356, 353, 54, 55))
        self.Piece15.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece15.setText("")
        self.Piece15.setObjectName("Piece15")
        self.Piece14 = QtWidgets.QLabel(parent=Form)
        self.Piece14.setGeometry(QtCore.QRect(301, 353, 54, 55))
        self.Piece14.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece14.setText("")
        self.Piece14.setObjectName("Piece14")
        self.Piece16 = QtWidgets.QLabel(parent=Form)
        self.Piece16.setGeometry(QtCore.QRect(411, 353, 54, 55))
        self.Piece16.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece16.setText("")
        self.Piece16.setObjectName("Piece16")
        self.Piece19 = QtWidgets.QLabel(parent=Form)
        self.Piece19.setGeometry(QtCore.QRect(136, 299, 54, 55))
        self.Piece19.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece19.setText("")
        self.Piece19.setObjectName("Piece19")
        self.Piece23 = QtWidgets.QLabel(parent=Form)
        self.Piece23.setGeometry(QtCore.QRect(356, 299, 54, 55))
        self.Piece23.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece23.setText("")
        self.Piece23.setObjectName("Piece23")
        self.Piece22 = QtWidgets.QLabel(parent=Form)
        self.Piece22.setGeometry(QtCore.QRect(301, 299, 54, 55))
        self.Piece22.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece22.setText("")
        self.Piece22.setObjectName("Piece22")
        self.Piece17 = QtWidgets.QLabel(parent=Form)
        self.Piece17.setGeometry(QtCore.QRect(27, 299, 54, 55))
        self.Piece17.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece17.setText("")
        self.Piece17.setObjectName("Piece17")
        self.Piece24 = QtWidgets.QLabel(parent=Form)
        self.Piece24.setGeometry(QtCore.QRect(411, 299, 54, 55))
        self.Piece24.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece24.setText("")
        self.Piece24.setObjectName("Piece24")
        self.Piece18 = QtWidgets.QLabel(parent=Form)
        self.Piece18.setGeometry(QtCore.QRect(82, 299, 54, 55))
        self.Piece18.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece18.setText("")
        self.Piece18.setObjectName("Piece18")
        self.Piece20 = QtWidgets.QLabel(parent=Form)
        self.Piece20.setGeometry(QtCore.QRect(191, 299, 54, 55))
        self.Piece20.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece20.setText("")
        self.Piece20.setObjectName("Piece20")
        self.Piece21 = QtWidgets.QLabel(parent=Form)
        self.Piece21.setGeometry(QtCore.QRect(246, 299, 54, 55))
        self.Piece21.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece21.setText("")
        self.Piece21.setObjectName("Piece21")
        self.Piece26 = QtWidgets.QLabel(parent=Form)
        self.Piece26.setGeometry(QtCore.QRect(82, 245, 54, 54))
        self.Piece26.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece26.setText("")
        self.Piece26.setObjectName("Piece26")
        self.Piece25 = QtWidgets.QLabel(parent=Form)
        self.Piece25.setGeometry(QtCore.QRect(27, 245, 54, 55))
        self.Piece25.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece25.setText("")
        self.Piece25.setObjectName("Piece25")
        self.Piece27 = QtWidgets.QLabel(parent=Form)
        self.Piece27.setGeometry(QtCore.QRect(136, 245, 54, 55))
        self.Piece27.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece27.setText("")
        self.Piece27.setObjectName("Piece27")
        self.Piece28 = QtWidgets.QLabel(parent=Form)
        self.Piece28.setGeometry(QtCore.QRect(191, 245, 54, 55))
        self.Piece28.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece28.setText("")
        self.Piece28.setObjectName("Piece28")
        self.Piece29 = QtWidgets.QLabel(parent=Form)
        self.Piece29.setGeometry(QtCore.QRect(246, 245, 54, 55))
        self.Piece29.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece29.setText("")
        self.Piece29.setObjectName("Piece29")
        self.Piece31 = QtWidgets.QLabel(parent=Form)
        self.Piece31.setGeometry(QtCore.QRect(356, 245, 54, 55))
        self.Piece31.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece31.setText("")
        self.Piece31.setObjectName("Piece31")
        self.Piece30 = QtWidgets.QLabel(parent=Form)
        self.Piece30.setGeometry(QtCore.QRect(301, 245, 54, 55))
        self.Piece30.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece30.setText("")
        self.Piece30.setObjectName("Piece30")
        self.Piece32 = QtWidgets.QLabel(parent=Form)
        self.Piece32.setGeometry(QtCore.QRect(411, 245, 54, 55))
        self.Piece32.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece32.setText("")
        self.Piece32.setObjectName("Piece32")
        self.Piece35 = QtWidgets.QLabel(parent=Form)
        self.Piece35.setGeometry(QtCore.QRect(136, 191, 54, 55))
        self.Piece35.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece35.setText("")
        self.Piece35.setObjectName("Piece35")
        self.Piece39 = QtWidgets.QLabel(parent=Form)
        self.Piece39.setGeometry(QtCore.QRect(356, 191, 54, 55))
        self.Piece39.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece39.setText("")
        self.Piece39.setObjectName("Piece39")
        self.Piece38 = QtWidgets.QLabel(parent=Form)
        self.Piece38.setGeometry(QtCore.QRect(301, 191, 54, 55))
        self.Piece38.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece38.setText("")
        self.Piece38.setObjectName("Piece38")
        self.Piece33 = QtWidgets.QLabel(parent=Form)
        self.Piece33.setGeometry(QtCore.QRect(27, 191, 54, 55))
        self.Piece33.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece33.setText("")
        self.Piece33.setObjectName("Piece33")
        self.Piece40 = QtWidgets.QLabel(parent=Form)
        self.Piece40.setGeometry(QtCore.QRect(411, 191, 54, 55))
        self.Piece40.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece40.setText("")
        self.Piece40.setObjectName("Piece40")
        self.Piece34 = QtWidgets.QLabel(parent=Form)
        self.Piece34.setGeometry(QtCore.QRect(82, 191, 54, 55))
        self.Piece34.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece34.setText("")
        self.Piece34.setObjectName("Piece34")
        self.Piece37 = QtWidgets.QLabel(parent=Form)
        self.Piece37.setGeometry(QtCore.QRect(191, 191, 54, 55))
        self.Piece37.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece37.setText("")
        self.Piece37.setObjectName("Piece37")
        self.Piece1_20 = QtWidgets.QLabel(parent=Form)
        self.Piece1_20.setGeometry(QtCore.QRect(246, 191, 54, 55))
        self.Piece1_20.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece1_20.setText("")
        self.Piece1_20.setObjectName("Piece1_20")
        self.Piece42 = QtWidgets.QLabel(parent=Form)
        self.Piece42.setGeometry(QtCore.QRect(82, 136, 54, 55))
        self.Piece42.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece42.setText("")
        self.Piece42.setObjectName("Piece42")
        self.Piece41 = QtWidgets.QLabel(parent=Form)
        self.Piece41.setGeometry(QtCore.QRect(27, 136, 54, 55))
        self.Piece41.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece41.setText("")
        self.Piece41.setObjectName("Piece41")
        self.Piece43 = QtWidgets.QLabel(parent=Form)
        self.Piece43.setGeometry(QtCore.QRect(136, 136, 54, 55))
        self.Piece43.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece43.setText("")
        self.Piece43.setObjectName("Piece43")
        self.Piece44 = QtWidgets.QLabel(parent=Form)
        self.Piece44.setGeometry(QtCore.QRect(191, 136, 54, 55))
        self.Piece44.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece44.setText("")
        self.Piece44.setObjectName("Piece44")
        self.Piece45 = QtWidgets.QLabel(parent=Form)
        self.Piece45.setGeometry(QtCore.QRect(246, 136, 54, 55))
        self.Piece45.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece45.setText("")
        self.Piece45.setObjectName("Piece45")
        self.Piece47 = QtWidgets.QLabel(parent=Form)
        self.Piece47.setGeometry(QtCore.QRect(356, 136, 54, 55))
        self.Piece47.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece47.setText("")
        self.Piece47.setObjectName("Piece47")
        self.Piece46 = QtWidgets.QLabel(parent=Form)
        self.Piece46.setGeometry(QtCore.QRect(301, 136, 54, 55))
        self.Piece46.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece46.setText("")
        self.Piece46.setObjectName("Piece46")
        self.Piece48 = QtWidgets.QLabel(parent=Form)
        self.Piece48.setGeometry(QtCore.QRect(411, 136, 54, 55))
        self.Piece48.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece48.setText("")
        self.Piece48.setObjectName("Piece48")
        self.Piece51 = QtWidgets.QLabel(parent=Form)
        self.Piece51.setGeometry(QtCore.QRect(136, 82, 54, 55))
        self.Piece51.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece51.setText("")
        self.Piece51.setObjectName("Piece51")
        self.Piece55 = QtWidgets.QLabel(parent=Form)
        self.Piece55.setGeometry(QtCore.QRect(356, 82, 54, 55))
        self.Piece55.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece55.setText("")
        self.Piece55.setObjectName("Piece55")
        self.Piece54 = QtWidgets.QLabel(parent=Form)
        self.Piece54.setGeometry(QtCore.QRect(301, 82, 54, 55))
        self.Piece54.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece54.setText("")
        self.Piece54.setObjectName("Piece54")
        self.Piece49 = QtWidgets.QLabel(parent=Form)
        self.Piece49.setGeometry(QtCore.QRect(27, 82, 54, 55))
        self.Piece49.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece49.setText("")
        self.Piece49.setObjectName("Piece49")
        self.Piece56 = QtWidgets.QLabel(parent=Form)
        self.Piece56.setGeometry(QtCore.QRect(411, 82, 54, 55))
        self.Piece56.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece56.setText("")
        self.Piece56.setObjectName("Piece56")
        self.Piece50 = QtWidgets.QLabel(parent=Form)
        self.Piece50.setGeometry(QtCore.QRect(82, 82, 54, 55))
        self.Piece50.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece50.setText("")
        self.Piece50.setObjectName("Piece50")
        self.Piece52 = QtWidgets.QLabel(parent=Form)
        self.Piece52.setGeometry(QtCore.QRect(191, 82, 54, 55))
        self.Piece52.setStyleSheet("image: url(design/chess_Figure/White.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece52.setText("")
        self.Piece52.setObjectName("Piece52")
        self.Piece53 = QtWidgets.QLabel(parent=Form)
        self.Piece53.setGeometry(QtCore.QRect(246, 82, 54, 55))
        self.Piece53.setStyleSheet("image: url(design/chess_Figure/Black.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.Piece53.setText("")
        self.Piece53.setObjectName("Piece53")
        self.wp1 = QtWidgets.QLabel(parent=Form)
        self.wp1.setGeometry(QtCore.QRect(27, 353, 54, 55))
        self.wp1.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp1.setText("")
        self.wp1.setObjectName("wp1")
        self.wp2 = QtWidgets.QLabel(parent=Form)
        self.wp2.setGeometry(QtCore.QRect(82, 353, 54, 55))
        self.wp2.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp2.setText("")
        self.wp2.setObjectName("wp2")
        self.wp8 = QtWidgets.QLabel(parent=Form)
        self.wp8.setGeometry(QtCore.QRect(411, 353, 54, 55))
        self.wp8.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp8.setText("")
        self.wp8.setObjectName("wp8")
        self.wp7 = QtWidgets.QLabel(parent=Form)
        self.wp7.setGeometry(QtCore.QRect(356, 353, 54, 55))
        self.wp7.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp7.setText("")
        self.wp7.setObjectName("wp7")
        self.wp6 = QtWidgets.QLabel(parent=Form)
        self.wp6.setGeometry(QtCore.QRect(301, 353, 54, 55))
        self.wp6.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp6.setText("")
        self.wp6.setObjectName("wp6")
        self.wp5 = QtWidgets.QLabel(parent=Form)
        self.wp5.setGeometry(QtCore.QRect(246, 353, 54, 55))
        self.wp5.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp5.setText("")
        self.wp5.setObjectName("wp5")
        self.wp4 = QtWidgets.QLabel(parent=Form)
        self.wp4.setGeometry(QtCore.QRect(191, 353, 54, 55))
        self.wp4.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp4.setText("")
        self.wp4.setObjectName("wp4")
        self.wp3 = QtWidgets.QLabel(parent=Form)
        self.wp3.setGeometry(QtCore.QRect(136, 353, 54, 55))
        self.wp3.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp3.setText("")
        self.wp3.setObjectName("wp3")
        self.wN1 = QtWidgets.QLabel(parent=Form)
        self.wN1.setGeometry(QtCore.QRect(82, 407, 54, 55))
        self.wN1.setStyleSheet("image:url(design/chess_Figure/wN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wN1.setText("")
        self.wN1.setObjectName("wN1")
        self.wN2 = QtWidgets.QLabel(parent=Form)
        self.wN2.setGeometry(QtCore.QRect(356, 407, 54, 55))
        self.wN2.setStyleSheet("image:url(design/chess_Figure/wN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wN2.setText("")
        self.wN2.setObjectName("wN2")
        self.wB1 = QtWidgets.QLabel(parent=Form)
        self.wB1.setGeometry(QtCore.QRect(136, 407, 54, 55))
        self.wB1.setStyleSheet("image:url(design/chess_Figure/wB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wB1.setText("")
        self.wB1.setObjectName("wB1")
        self.wB2 = QtWidgets.QLabel(parent=Form)
        self.wB2.setGeometry(QtCore.QRect(301, 407, 54, 55))
        self.wB2.setStyleSheet("image:url(design/chess_Figure/wB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wB2.setText("")
        self.wB2.setObjectName("wB2")
        self.wK = QtWidgets.QLabel(parent=Form)
        self.wK.setGeometry(QtCore.QRect(246, 407, 54, 55))
        self.wK.setStyleSheet("image:url(design/chess_Figure/wK.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wK.setText("")
        self.wK.setObjectName("wK")
        self.wQ = QtWidgets.QLabel(parent=Form)
        self.wQ.setGeometry(QtCore.QRect(191, 407, 54, 55))
        self.wQ.setStyleSheet("image:url(design/chess_Figure/wQ.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wQ.setText("")
        self.wQ.setObjectName("wQ")
        self.bp1 = QtWidgets.QLabel(parent=Form)
        self.bp1.setGeometry(QtCore.QRect(27, 82, 54, 55))
        self.bp1.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp1.setText("")
        self.bp1.setObjectName("bp1")
        self.bp5 = QtWidgets.QLabel(parent=Form)
        self.bp5.setGeometry(QtCore.QRect(246, 82, 54, 55))
        self.bp5.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp5.setText("")
        self.bp5.setObjectName("bp5")
        self.bp4 = QtWidgets.QLabel(parent=Form)
        self.bp4.setGeometry(QtCore.QRect(191, 82, 54, 55))
        self.bp4.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp4.setText("")
        self.bp4.setObjectName("bp4")
        self.bp3 = QtWidgets.QLabel(parent=Form)
        self.bp3.setGeometry(QtCore.QRect(136, 82, 54, 55))
        self.bp3.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp3.setText("")
        self.bp3.setObjectName("bp3")
        self.bp2 = QtWidgets.QLabel(parent=Form)
        self.bp2.setGeometry(QtCore.QRect(82, 82, 54, 55))
        self.bp2.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp2.setText("")
        self.bp2.setObjectName("bp2")
        self.bp8 = QtWidgets.QLabel(parent=Form)
        self.bp8.setGeometry(QtCore.QRect(411, 82, 54, 55))
        self.bp8.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp8.setText("")
        self.bp8.setObjectName("bp8")
        self.bp6 = QtWidgets.QLabel(parent=Form)
        self.bp6.setGeometry(QtCore.QRect(301, 82, 54, 55))
        self.bp6.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp6.setText("")
        self.bp6.setObjectName("bp6")
        self.bp7 = QtWidgets.QLabel(parent=Form)
        self.bp7.setGeometry(QtCore.QRect(356, 82, 54, 55))
        self.bp7.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp7.setText("")
        self.bp7.setObjectName("bp7")
        self.bR1 = QtWidgets.QLabel(parent=Form)
        self.bR1.setGeometry(QtCore.QRect(27, 28, 54, 55))
        self.bR1.setStyleSheet("image:url(design/chess_Figure/bR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bR1.setText("")
        self.bR1.setObjectName("bR1")
        self.br2 = QtWidgets.QLabel(parent=Form)
        self.br2.setGeometry(QtCore.QRect(411, 28, 54, 55))
        self.br2.setStyleSheet("image:url(design/chess_Figure/bR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.br2.setText("")
        self.br2.setObjectName("br2")
        self.bN1 = QtWidgets.QLabel(parent=Form)
        self.bN1.setGeometry(QtCore.QRect(82, 28, 54, 55))
        self.bN1.setStyleSheet("image:url(design/chess_Figure/bN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bN1.setText("")
        self.bN1.setObjectName("bN1")
        self.bN2 = QtWidgets.QLabel(parent=Form)
        self.bN2.setGeometry(QtCore.QRect(356, 28, 54, 55))
        self.bN2.setStyleSheet("image:url(design/chess_Figure/bN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bN2.setText("")
        self.bN2.setObjectName("bN2")
        self.bB1 = QtWidgets.QLabel(parent=Form)
        self.bB1.setGeometry(QtCore.QRect(136, 28, 54, 55))
        self.bB1.setStyleSheet("image:url(design/chess_Figure/bB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bB1.setText("")
        self.bB1.setObjectName("bB1")
        self.bB2 = QtWidgets.QLabel(parent=Form)
        self.bB2.setGeometry(QtCore.QRect(301, 28, 54, 55))
        self.bB2.setStyleSheet("image:url(design/chess_Figure/bB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bB2.setText("")
        self.bB2.setObjectName("bB2")
        self.bK = QtWidgets.QLabel(parent=Form)
        self.bK.setGeometry(QtCore.QRect(246, 28, 54, 55))
        self.bK.setStyleSheet("image:url(design/chess_Figure/bK.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bK.setText("")
        self.bK.setObjectName("bK")
        self.bQ = QtWidgets.QLabel(parent=Form)
        self.bQ.setGeometry(QtCore.QRect(191, 28, 54, 55))
        self.bQ.setStyleSheet("image:url(design/chess_Figure/bQ.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bQ.setText("")
        self.bQ.setObjectName("bQ")
        self.BoardLabel.raise_()
        self.Piece1.raise_()
        self.Piece2.raise_()
        self.Piece4.raise_()
        self.Piece3.raise_()
        self.Piece7.raise_()
        self.Piece6.raise_()
        self.Piece5.raise_()
        self.Piece8.raise_()
        self.Piece58.raise_()
        self.Piece57.raise_()
        self.Piece60.raise_()
        self.Piece59.raise_()
        self.Piece62.raise_()
        self.Piece61.raise_()
        self.Piece63.raise_()
        self.Piece64.raise_()
        self.Piece10.raise_()
        self.Piece9.raise_()
        self.Piece11.raise_()
        self.Piece12.raise_()
        self.Piece13.raise_()
        self.Piece15.raise_()
        self.Piece14.raise_()
        self.Piece16.raise_()
        self.Piece19.raise_()
        self.Piece23.raise_()
        self.Piece22.raise_()
        self.Piece17.raise_()
        self.Piece24.raise_()
        self.Piece18.raise_()
        self.Piece20.raise_()
        self.Piece21.raise_()
        self.Piece26.raise_()
        self.Piece25.raise_()
        self.Piece27.raise_()
        self.Piece28.raise_()
        self.Piece29.raise_()
        self.Piece31.raise_()
        self.Piece30.raise_()
        self.Piece32.raise_()
        self.Piece35.raise_()
        self.Piece39.raise_()
        self.Piece38.raise_()
        self.Piece33.raise_()
        self.Piece40.raise_()
        self.Piece34.raise_()
        self.Piece37.raise_()
        self.Piece1_20.raise_()
        self.Piece42.raise_()
        self.Piece41.raise_()
        self.Piece43.raise_()
        self.Piece44.raise_()
        self.Piece45.raise_()
        self.Piece47.raise_()
        self.Piece46.raise_()
        self.Piece48.raise_()
        self.Piece51.raise_()
        self.Piece55.raise_()
        self.Piece54.raise_()
        self.Piece49.raise_()
        self.Piece56.raise_()
        self.Piece50.raise_()
        self.Piece52.raise_()
        self.Piece53.raise_()
        self.wp1.raise_()
        self.wp2.raise_()
        self.wp8.raise_()
        self.wp7.raise_()
        self.wp6.raise_()
        self.wp5.raise_()
        self.wp4.raise_()
        self.wp3.raise_()
        self.wN1.raise_()
        self.wN2.raise_()
        self.wB1.raise_()
        self.wB2.raise_()
        self.wK.raise_()
        self.wQ.raise_()
        self.bp1.raise_()
        self.wR2.raise_()
        self.wR1.raise_()
        self.bp5.raise_()
        self.bp4.raise_()
        self.bp3.raise_()
        self.bp2.raise_()
        self.bp8.raise_()
        self.bp6.raise_()
        self.bp7.raise_()
        self.bR1.raise_()
        self.br2.raise_()
        self.bN1.raise_()
        self.bN2.raise_()
        self.bB1.raise_()
        self.bB2.raise_()
        self.bK.raise_()
        self.bQ.raise_()

        self.LableMove = QtWidgets.QLabel(parent=Form)
        self.LableMove.setGeometry(QtCore.QRect(246, 482, 80, 80))
        self.LableMove.setText("Ход белых")
        self.LableMove.setObjectName("LableMove")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LableMove.setFont(font)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)




    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
