# Form implementation generated from reading ui file 'newTEST.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtGui import QCursor


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(765, 677)
        Form.setStyleSheet("и")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(-12, 0, 491, 461))
        self.label_2.setStyleSheet("image:url(design/chess_Figure/1451.jpg)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.bp3 = QtWidgets.QPushButton(parent=Form)
        self.bp3.setGeometry(QtCore.QRect(131, 77, 46, 46))
        self.bp3.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp3.setText("")
        self.bp3.setObjectName("bp3")
        self.bp2 = QtWidgets.QPushButton(parent=Form)
        self.bp2.setGeometry(QtCore.QRect(80, 77, 46, 46))
        self.bp2.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp2.setText("")
        self.bp2.setObjectName("bp2")
        self.bp4 = QtWidgets.QPushButton(parent=Form)
        self.bp4.setGeometry(QtCore.QRect(182, 77, 46, 46))
        self.bp4.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp4.setText("")
        self.bp4.setObjectName("bp4")
        self.bp1 = QtWidgets.QPushButton(parent=Form)
        self.bp1.setGeometry(QtCore.QRect(28, 77, 46, 46))
        self.bp1.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp1.setText("")
        self.bp1.setObjectName("bp1")
        self.bp6 = QtWidgets.QPushButton(parent=Form)
        self.bp6.setGeometry(QtCore.QRect(286, 77, 46, 46))
        self.bp6.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp6.setText("")
        self.bp6.setObjectName("bp6")
        self.bp5 = QtWidgets.QPushButton(parent=Form)
        self.bp5.setGeometry(QtCore.QRect(234, 77, 46, 46))
        self.bp5.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp5.setText("")
        self.bp5.setObjectName("bp5")
        self.bp8 = QtWidgets.QPushButton(parent=Form)
        self.bp8.setGeometry(QtCore.QRect(390, 77, 46, 46))
        self.bp8.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp8.setText("")
        self.bp8.setObjectName("bp8")
        self.bp7 = QtWidgets.QPushButton(parent=Form)
        self.bp7.setGeometry(QtCore.QRect(338, 77, 46, 46))
        self.bp7.setStyleSheet("image:url(design/chess_Figure/bp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bp7.setText("")
        self.bp7.setObjectName("bp7")
        self.wp1 = QtWidgets.QPushButton(parent=Form)
        self.wp1.setGeometry(QtCore.QRect(28, 337, 46, 46))
        self.wp1.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp1.setText("")
        self.wp1.setObjectName("wp1")
        self.wp3 = QtWidgets.QPushButton(parent=Form)
        self.wp3.setGeometry(QtCore.QRect(131, 337, 46, 46))
        self.wp3.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp3.setText("")
        self.wp3.setObjectName("wp3")
        self.wp2 = QtWidgets.QPushButton(parent=Form)
        self.wp2.setGeometry(QtCore.QRect(80, 337, 46, 46))
        self.wp2.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp2.setText("")
        self.wp2.setObjectName("wp2")
        self.wp6 = QtWidgets.QPushButton(parent=Form)
        self.wp6.setGeometry(QtCore.QRect(286, 337, 46, 46))
        self.wp6.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp6.setText("")
        self.wp6.setObjectName("wp6")
        self.wp4 = QtWidgets.QPushButton(parent=Form)
        self.wp4.setGeometry(QtCore.QRect(182, 337, 46, 46))
        self.wp4.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp4.setText("")
        self.wp4.setObjectName("wp4")
        self.wp5 = QtWidgets.QPushButton(parent=Form)
        self.wp5.setGeometry(QtCore.QRect(234, 337, 46, 46))
        self.wp5.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp5.setText("")
        self.wp5.setObjectName("wp5")
        self.w = QtWidgets.QPushButton(parent=Form)
        self.w.setGeometry(QtCore.QRect(390, 337, 46, 46))
        self.w.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.w.setText("")
        self.w.setObjectName("w")
        self.wp7 = QtWidgets.QPushButton(parent=Form)
        self.wp7.setGeometry(QtCore.QRect(338, 337, 46, 46))
        self.wp7.setStyleSheet("image:url(design/chess_Figure/wp.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp7.setText("")
        self.wp7.setObjectName("wp7")
        self.wR1 = QtWidgets.QPushButton(parent=Form)
        self.wR1.setGeometry(QtCore.QRect(28, 389, 46, 46))
        self.wR1.setStyleSheet("image:url(design/chess_Figure//wR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wR1.setText("")
        self.wR1.setObjectName("wR1")
        self.wR2 = QtWidgets.QPushButton(parent=Form)
        self.wR2.setGeometry(QtCore.QRect(389, 389, 46, 46))
        self.wR2.setStyleSheet("image:url(design/chess_Figure/wR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wR2.setText("")
        self.wR2.setObjectName("wR2")
        self.wN1 = QtWidgets.QPushButton(parent=Form)
        self.wN1.setGeometry(QtCore.QRect(80, 389, 46, 46))
        self.wN1.setStyleSheet("image:url(design/chess_Figure/wN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wN1.setText("")
        self.wN1.setObjectName("wN1")
        self.wN2 = QtWidgets.QPushButton(parent=Form)
        self.wN2.setGeometry(QtCore.QRect(338, 389, 46, 46))
        self.wN2.setStyleSheet("image:url(design/chess_Figure/wN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wN2.setText("")
        self.wN2.setObjectName("wN2")
        self.wB1 = QtWidgets.QPushButton(parent=Form)
        self.wB1.setGeometry(QtCore.QRect(131, 389, 46, 46))
        self.wB1.setStyleSheet("image:url(design/chess_Figure/wB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wB1.setText("")
        self.wB1.setObjectName("wB1")
        self.wB2 = QtWidgets.QPushButton(parent=Form)
        self.wB2.setGeometry(QtCore.QRect(286, 389, 46, 46))
        self.wB2.setStyleSheet("image:url(design/chess_Figure/wB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wB2.setText("")
        self.wB2.setObjectName("wB2")
        self.wQ = QtWidgets.QPushButton(parent=Form)
        self.wQ.setGeometry(QtCore.QRect(182, 387, 46, 46))
        self.wQ.setStyleSheet("image:url(design/chess_Figure/wQ.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wQ.setText("")
        self.wQ.setObjectName("wQ")
        self.wp1_6 = QtWidgets.QPushButton(parent=Form)
        self.wp1_6.setGeometry(QtCore.QRect(234, 389, 46, 46))
        self.wp1_6.setStyleSheet("image:url(design/chess_Figure/wK.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.wp1_6.setText("")
        self.wp1_6.setObjectName("wp1_6")
        self.bR1 = QtWidgets.QPushButton(parent=Form)
        self.bR1.setGeometry(QtCore.QRect(28, 25, 46, 46))
        self.bR1.setStyleSheet("image:url(design/chess_Figure/bR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bR1.setText("")
        self.bR1.setObjectName("bR1")
        self.bB1 = QtWidgets.QPushButton(parent=Form)
        self.bB1.setGeometry(QtCore.QRect(131, 25, 46, 46))
        self.bB1.setStyleSheet("image:url(design/chess_Figure/bB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bB1.setText("")
        self.bB1.setObjectName("bB1")
        self.bN1 = QtWidgets.QPushButton(parent=Form)
        self.bN1.setGeometry(QtCore.QRect(80, 25, 46, 46))
        self.bN1.setStyleSheet("image:url(design/chess_Figure/bN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bN1.setText("")
        self.bN1.setObjectName("bN1")
        self.bK = QtWidgets.QPushButton(parent=Form)
        self.bK.setGeometry(QtCore.QRect(234, 25, 46, 46))
        self.bK.setStyleSheet("image:url(design/chess_Figure/bK.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bK.setText("")
        self.bK.setObjectName("bK")
        self.bQ = QtWidgets.QPushButton(parent=Form)
        self.bQ.setGeometry(QtCore.QRect(182, 25, 46, 46))
        self.bQ.setStyleSheet("image:url(design/chess_Figure/bQ.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bQ.setText("")
        self.bQ.setObjectName("bQ")
        self.bN2 = QtWidgets.QPushButton(parent=Form)
        self.bN2.setGeometry(QtCore.QRect(338, 25, 46, 46))
        self.bN2.setStyleSheet("image:url(design/chess_Figure/bN.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bN2.setText("")
        self.bN2.setObjectName("bN2")
        self.bB2 = QtWidgets.QPushButton(parent=Form)
        self.bB2.setGeometry(QtCore.QRect(286, 25, 46, 46))
        self.bB2.setStyleSheet("image:url(design/chess_Figure/bB.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bB2.setText("")
        self.bB2.setObjectName("bB2")
        self.bR2 = QtWidgets.QPushButton(parent=Form)
        self.bR2.setGeometry(QtCore.QRect(389, 25, 46, 46))
        self.bR2.setStyleSheet("image:url(design/chess_Figure/bR.png);\n"
"borded: none;\n"
"background-color: rgba(255,255,255,0);")
        self.bR2.setText("")
        self.bR2.setObjectName("bR2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.add_functions()

    def add_functions(self):
        self.bR2.clicked.connect(self.myF)

    def myF(self):
        print("TEST TEST")
        # self.bR2.close() - закрывает кнопку
        #
        # lox = self.bR2.x() - 52
        # lox2 = self.bR2.y() + 52
        #
        #
        # self.bR2.setGeometry(QtCore.QRect(lox, lox2, 46, 46)) # - пример движения кнопки

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

